trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - "*/*.md"
      - "*/*.txt"

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: Build
        timeoutInMinutes: 360
        cancelTimeoutInMinutes: 1
        pool:
          name: Default
          demands:
            - agent.os -equals Windows_NT

        steps:
          - task: Docker@2
            displayName: "Build image"
            inputs:
              command: build
              containerRegistry: "Docker Lambda3"
              repository: "lambda3/vs-extensions-gallery"
              tags: latest
              Dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              arguments: "--network lan_net"

          - task: Docker@2
            displayName: "Push image"
            inputs:
              containerRegistry: "Docker Lambda3"
              repository: "lambda3/vs-extensions-gallery"
              command: push
              tags: latest
